### ISSUE TITLE
Spawnrate not working

### ISSUE THREAD

**Issue by NielsDenoo** [SimonStnn/pop-a-loon#164]
The spawnrate option in settings is X

![image](https://github.com/SimonStnn/pop-a-loon/assets/145467399/e4c4df01-82b9-4b46-b329-bd9319fae50a)

**Comment by SimonStnn** [comment]
Thank you for the bug report. Working on it now.

**Comment by SimonStnn** [comment]
The issue was that the initial config is not being set correctly if it has changed.

https://github.com/SimonStnn/pop-a-loon/blob/8bc5743d935191d233fd1d44e936454265b2c521/src/background/background.ts#L70-L72

Even if there is a config already, it should still take the initial config in consideration.
